#!/bin/bash
version="1.2 beta 2/2/2021"

if [ $EUID -ne 0 ]; then
    echo "Error: Root user is required to execute.."
    exit 1
fi

#source /etc/update/update.conf
source /var/lib/update/shared_functions

# Repositories update function
update_ () {
    log_ "Updating local package repositories."
    #apt update -qq > /dev/null 2>&1
    if apt update -qq > /dev/null 2>&1; then
        info_ "Local package repositories updated successfully."
    else
        error_ "Error: Local package repositories failed to update."
    fi
}

# Update only security packages
apt-security() {
    log_ "Upgrading only security packages."
    #local tmp_list=$(mktemp /tmp/update-XXXX)
    local tmp_list=/tmp/security.list.$$
    local list=/etc/apt/sources.list

    if [ ! -f $list ]; then
        error_ "Error: No sources.list found."
        return
    fi

    grep "security" $list | grep -v "src" | cut -d "#" -f 2 > $tmp_list \
        && log_ "Security sources list created."

    apt upgrade -V -o Dir::Etc::SourceLst=$tmp_list
    rm $tmp_list && log_ "Security sources list removed."
}

# Print list of sources list files available to edit
sources() {
    # if no filename given
    if [ -z "$1" ]; then
        # print list of sources list files
        local local i=1
        for f in $(find /etc/apt/ -type f -iname "*.list" -printf "%f\n"); do
            lists[$i]="$f"
            echo "$i) $f"
            ((i++))
        done

        lists[$i]="Return Back"
        echo -e "\n$i) ${lists[$i]}\n"
        read -p "Enter source list number [1]: " i

        # report invalid option and exit
        case ${lists[$i]} in
            '') error_ "Error: No source list found. Must be number within range."
                return ;;
            "Return Back") return ;;
        esac

        # Set list name to edit
        local list="${lists[$i]}"

    # in case filename is given check if file exists, else report and exit
    elif [[ -f $(find /etc/apt/ -type f -iname "$1") ]]; then
        local list=$1
    else
        error_ "Error: $1 file not found, try again..."
        return
    fi

    log_ "Editing sources file: $list"

    # apt tries to create new file in case of sources.list
    if [ "$list" == "sources.list" ]; then
        unset list
    fi

    # edit source list command
    apt edit-sources ${list}

    # Ask to update package repositories
    read -p "Update package repositories no? [Y/n]: "
    case $REPLY in
        y|Y|'') update_ ;;
        *) warning_ "Warning: Package repositories not updated after sources list update." ;;
    esac
}

vers() {
    info_ "System-Update\nVersion: $version"
    info_ "Github page: https://github.com/sianios/system-update"
}

# Find the fastest repository to download packages, works only on Debian
fastest-mirror() {
    if [ "$(lsb_release -is)" != "Debian" ]; then
        error_ "Your distro does not support this function."
        return
    fi

    local sources="/etc/apt/sources.list"
    if [ ! -f $sources ]; then
        error_ "Error: $sources not found."
        return
    fi

    # remove comments
    local file
    file=$(grep -v '#' $sources)
    # arguments variable
    local args

    # Check if deb-src are enabled
    if grep -q 'deb-src' "$file"; then
        args="$args -s"
    fi

    # Check if non-free is enabled
    if ! grep -q 'non-free' "$file"; then
        args="$args -n"
    fi

    # check system release, if not testing select stable
    local release
    release=$(lsb_release -rs)
    if [ "$release" != "testing" ]; then
        unset release
    fi


    # ask user to overide original sources.list or not
    read -p "Overide original sources.list? [Y/n]: "
    case $REPLY in
        y|Y|'') local sources_backup
            sources_backup="$sources.$(date "+%Y_%m_%d_%H_%M")"
            cp $sources "$sources_backup"
            info_ "Info: $sources backup created $sources_backup"
            ;;
        *) sources="/tmp/sources.list"
            ;;
    esac

    args="$args -o $sources"
    info_ "netselect-apt saving in $sources"

    args="netselect-apt $release $args"
    eval "$args"
}

# Find and remove old kernels from system
purge_kernels() {
    # find which kernel the system loaded on boot
    local loaded=$(uname -r)
    # get list of old installed kernels
    local kernels=($(linux-version list | grep -v $loaded | cut -d "-" -f -2))
    # check if any kernels found and report
    if [ -z ${kernels[0]} ]; then
        info_ "Info: No Linux kernels found to remove."
        return
    fi

    ### create a list of packages to be removed from system
    local pkgs
    local i
    for i in "${!kernels[@]}"; do
        pkgs="$pkgs $(dpkg --get-selections | grep "${kernels[$i]}" | awk '{print $1}')"
    done

    warning_ "Warning: Removing Linux kernel packages might brake your system! Proceed with care and your own risk!"
    read -p "Proceed removing old kernels? [y/n]: "

    case $REPLY in
        y|Y) apt purge ${pkgs[*]}
            log_ "Packages removed: ${pkgs[*]}" ;;
        *) info_ "Removing kernel packages canceled."
            return ;;
    esac
}

# Enable and disable auto package repositories update using cron
auto_repo() {
    # cron file
    local cronf=/etc/crontab

    # If found in cron file auto update is enabled
    #grep cron.sh $cronf > /dev/null 2>&1
    grep -q cron.sh $cronf

    if [ $? == 0 ]; then
        info_ "Auto package repositories update is enabled."
        read -p "Disable auto repositories update? [Y/n]: "
        case $REPLY in
            y|Y|"") sed -i '/cron.sh/d' $cronf
                /etc/init.d/cron restart > /dev/null 2>&1 && log_ "Service Restarted: cron"
                info_ "Auto package repositories update disabled." ;;
            *) info_ "Auto package repositories update not disabled." ;;
        esac
    else
        info_ "Auto package repositories update is disabled."
        read -p "Enable auto repositories update? [Y/n]: "
        case $REPLY in
            y|Y|"") read -p "Auto package repositories update interval, input examples here: https://crontab.guru [Default: 2 hours]: "
                if [ -n $REPLY ]; then
                    REPLY="* */2 * * *"
                fi
                #echo "@daily sianios /var/lib/update/cron.sh > /dev/null 2>&1" >> $cronf
                echo "$REPLY root /var/lib/update/cron.sh > /dev/null 2>&1" >> $cronf
                /etc/init.d/cron restart > /dev/null 2>&1 && log_ "Service Restarted: cron"
                info_ "Auto package repositories update enabled." ;;
            *) info_ "Auto package repositories update not enabled." ;;
        esac
    fi
}

# Function to check for new script version
check_update() {
    info_ "Info: Checking online for new script version."
    local online_version=$(git ls-remote --tags https://github.com/sianios/system-update.git \
        | grep -v "{" | awk '{print $NF}' | tail -n1 | tr -d "refs/tags/v")

    # If local version is different with online download and update
    if [ "$online_version" != "$version" ]; then
        info_ "Info: New version available. Downloading now."
        # Download install script
        wget --quiet -O /tmp/install https://git.io/JfO2z && info_ "Info: Download complete."
        # parce option in install script and skip version check
        info_ "Info: Starting upgrade."
        bash /tmp/install f
    else # If the same report to user
        info_ "Info: System Update script latest version already installed."
    fi
}

help() {
cat <<EOF | column -L -t -s "|"
    Usage: update [option]

    Options:|Description:
    1, update|Update local repositories
    2, upgrade|Install available packages upgrades
    3, full-upgrade|Full-Upgrade install packages held back
    s, security|Upgrade only security packages
    l, list|List available packages upgrades
    a, autoremove|Autoremove useless packages
    k, remove-kernels|Remove old Linux kernels
    u, check-update|Check online for new version and update
    c, clear|Clean localy store packages
    f, fastest-mirror|Find the fastest mirror
    e, sources|Edit repositories sources list files
    r, auto-update|Enable or disable auto package repositories update
    h, history|View your apt history log
    m, menu|Print this help menu
    v, version|Print version
    q, quit|Exit running script
EOF
}

welcome() {
    if [ -z $flag ]; then
        info_ "Welcome to Systerm Update Script!\n"
        flag=1
    fi
}

main() {
    case $1 in
        1|update) update_ ;;
        2|upgrade) log_ "Packages upgrade." && apt upgrade -V -qq ;;
        3|full-upgrade) log_ "Full packages upgrade." && apt full-upgrade -V -qq ;;
        s|security) apt-security ;;
        l|list) log_ "Listing available packages upgrade." && apt list --upgradable ;;
        a|autoremove) log_ "Packages autoremove." && apt autoremove --purge ;;
        k|remove-kernels) purge_kernels ;;
        c|clear) log_ "Cleaning localy stored packages." && apt clean ;;
        e|sources) sources $2 ;;
        f|fastest-mirror) fastest-mirror ;;
        r|auto-update) auto_repo ;;
        h|history) less -N /var/log/apt/history.log ;;
        m|menu) help ;;
        u|check-update) check_update ;;
        v|version) vers ;;
        q|quit) exit 0 ;;
        ?*) error_ "Error: '$1' option not available. Try option 'm' for menu." ;;
    esac
}

while true; do

    if [ ! -z $1 ]; then
        main $1 $2
        break
    fi

    welcome
    read -p "Enter option (m - menu): "
    main $REPLY

done
