#!/bin/bash
version="1.1.3"

if [ $EUID -ne 0 ]; then
    echo "Error: Root user is required to execute.."
    exit 1
fi

# color functions
#red
error_() {
    echo $(tput setaf 1)$@$(tput sgr0)
}
#green
info_() {
    echo -e $(tput setaf 2)$@$(tput sgr0)
}
#yellow
warning_() {
    echo $(tput setaf 3)$@$(tput sgr0)
}

apt-security() {
    local tmp_list=$(mktemp /tmp/update-XXXX)
    local list=/etc/apt/sources.list

    if [ ! -f $list ]; then
        return
    fi

    grep "security" $list | grep -v "src" | cut -d "#" -f 2 > $tmp_list

    apt upgrade -V -o Dir::Etc::SourceList=$tmp_list
    rm $tmp_list
}

sources() {
    # if no filename given
    if [ -z $1 ]; then
        # print list of sources list files
        local i=1
        for f in $(find /etc/apt/ -type f -iname *.list -printf "%f\n"); do
            local lists[$i]="$f"
            echo "$i) $f"
            ((i++))
        done

        lists[$i]="Return Back"
        echo -e "\n$i) ${lists[$i]}\n"
        read -p "Enter source list number [1]: " i

        case ${lists[$i]} in
            '') error_ "Error: No source list found. Must be number within range."
                return ;;
            "Return Back") return ;;
        esac

        # Set list name to edit
        local list="${lists[$i]}"

    # in case filename is given check if file exists
    elif [[ -f $(find /etc/apt/ -type f -iname $1) ]]; then
        local list=$1
    else
        error_ "Error: $1 file not found, try again..."
        return
    fi

    # apt tries to create new file in case of sources.list
    if [ $list == "sources.list" ]; then
        unset list
    fi
    apt edit-sources $list

    read -p "Update package repositories now? [Y/n]: "
    case $REPLY in
        y|Y|'') apt update -qq ;;
        *) warning_ "Warning: Repositories not updated." ;;
    esac
}

vers() {
    info_ "System-Update\nVersion: "$version
    info_ "Github page: https://github.com/sianios/system-update"
}

help() {
cat <<EOF
    Usage: update [option]

    Options:
    1   Update local repositories
    2   Install available packages upgrades
    3   Full-Upgrade install packages held back
    s   Upgrade only security packages
    l   List available packages upgrades
    a   Autoremove useless packages
    c   Clean localy store packages
    e   Edit repositorie sources list files
    h   View your apt history log
    m   Print this help menu
    v   Print version
    q   Exit running script
EOF
}

welcome() {
    if [ -z $flag ]; then
        info_ "Welcome to Systerm Update Script!\n"
        flag=1
    fi
}

main() {
    case $1 in
        1) apt update -qq ;;
        2) apt upgrade -V -qq ;;
        3) apt full-upgrade -V -qq ;;
        s) apt-security ;;
        l) apt list --upgradable ;;
        a) apt autoremove --purge ;;
        c) apt clean ;;
        e) sources $2 ;;
        h) less -N /var/log/apt/history.log ;;
        m) help ;;
        v) vers ;;
        q) exit 0 ;;
        ?*) error_ "Error: $1 option not available, try again..." ;;
    esac
}

while true; do

    if [ ! -z $1 ]; then
        main ${1//-} $2
        break
    fi

    welcome
    read -p "Enter option (m - menu): "
    main $REPLY

done
